version: "3.5"

services:
  pg:
    image: postgres:11.6
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - "./database/:/docker-entrypoint-initdb.d/"
